[tool.poetry]
name = "mistral-bitnet"
version = "0.1.0"
description = ""
authors = ["William Shi <33271663+wx02shi@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
